# Generated by Django 3.0.2 on 2020-01-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roll_no',
            new_name='lname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud_class',
        ),
    ]
